//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoccerAndroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixtures
    {
        public int Idnr { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string League { get; set; }
        public string Round { get; set; }
        public string HomeTeam { get; set; }
        public Nullable<int> HomeTeam_Id { get; set; }
        public string AwayTeam { get; set; }
        public string AwayTeam_Id { get; set; }
        public string Location { get; set; }
        public Nullable<int> HomeGoals { get; set; }
        public Nullable<int> AwayGoals { get; set; }
        public string Time { get; set; }
        public string HomeTeamYellowCardDetails { get; set; }
        public string AwayTeamYellowCardDetails { get; set; }
        public string HomeTeamRedCardDetails { get; set; }
        public string AwayTeamRedCardDetails { get; set; }
        public string HomeLineupGoalkeeper { get; set; }
        public string AwayLineupGoalkeeper { get; set; }
        public string HomeLineupDefense { get; set; }
        public string AwayLineupDefense { get; set; }
        public string HomeLineupMidfield { get; set; }
        public string AwayLineupMidfield { get; set; }
        public string HomeLineupForward { get; set; }
        public string AwayLineupForward { get; set; }
        public string HomeLineupSubstitutes { get; set; }
        public string AwayLineupSubstitutes { get; set; }
        public string HomeGoalDetails { get; set; }
        public string AwayGoalDetails { get; set; }
        public string Referee { get; set; }
    }
}
