//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoccerAndroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int Id { get; set; }
        public Nullable<int> Playerid { get; set; }
        public string Name { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Team_Id { get; set; }
        public Nullable<int> PlayerNumber { get; set; }
        public string DateOfBirth { get; set; }
        public string DateOfSigning { get; set; }
        public string Signing { get; set; }
    }
}
