//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoccerAndroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLeagueStandings
    {
        public int id { get; set; }
        public string Liga { get; set; }
        public string Team { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> PlayedAtHome { get; set; }
        public Nullable<int> PlayedAway { get; set; }
        public Nullable<int> Won { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Goals_For { get; set; }
        public Nullable<int> Goals_Against { get; set; }
        public Nullable<int> Goal_Difference { get; set; }
        public Nullable<int> Points { get; set; }
    }
}
