//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoccerAndroid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int Id { get; set; }
        public Nullable<int> Team_Id { get; set; }
        public string Name { get; set; }
        public string Country_ { get; set; }
        public string Stadium_ { get; set; }
        public string HomePageURL_ { get; set; }
        public string WIKILink_ { get; set; }
    }
}
